name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main  # or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute SSH commands on Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/portfolio.dallah.co.ke
            git pull origin main
            systemctl reload nginx